version: '3'

services:
  server:
    volumes:
      - solexa:/mnt/solexa:ro

volumes:
  solexa:
    driver: local
    driver_opts:
     {type: 'nfs', device: ':/srv/nfs4/solexa', o: 'addr=bioaps01,ro,resvport'}
