version: '3'

services:
  server:
    build: .
    environment:
      - POSTGRES_PASSWORD=postgres
    entrypoint: /entrypoint.sh
    expose:
      - "5432"
    command: postgres -c config_file='/conf/postgresql.conf'
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./conf:/conf:ro
      - ./conf.d:/conf.d:ro
      - ./initdb.d:/initdb.d:ro
      - solexa:/mnt/solexa:ro

volumes:
  solexa:
    driver: local
    driver_opts:
     {type: 'nfs', device: ':/srv/nfs4/solexa', o: 'addr=bioaps01,ro,resvport'}

