version: '2'
services:
  server:
    build: .
    entrypoint: /entrypoint.sh
    environment:
      - POSTGRES_PASSWORD=postgres
    command: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - /mnt/solexa:/mnt/solexa
