version: '3'

services:
  server:
    image: visagie/mypg:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    entrypoint: /entrypoint.sh
    expose:
      - "5432"
    command: postgres -c config_file='/conf/postgresql.conf'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data
      - ./conf:/conf:ro
      - ./conf.d:/conf.d:ro
      - ./initdb.d:/initdb.d:ro
      - ./logs:/logs

volumes:
  pgdata:
